#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------------------------------------------------------------------------
# AGH LLM Suite — Entrypoint
# Usage: sudo bash llm-setup-bundle.sh [--bundle 1|2|3] [--pod-index 1-10]
#
# Bundle 1: Ollama + API (single key, no admin)
# Bundle 2: Ollama + API (multi-key, admin mint/list/revoke)
# Bundle 3: Bundle 2 + Virtual Desktop + UduChat (XFCE + Open WebUI)
#
# --pod-index: which pod slot to provision (1-10, default 1)
#              each pod gets its own ports + cloudflared URLs
#              allows multiple users on the same GPU
# ---------------------------------------------------------------------------

BUNDLE="${BUNDLE:-2}"
POD_INDEX="${POD_INDEX:-1}"

usage() {
  echo "Usage: sudo bash llm-setup-bundle.sh [--bundle 1|2|3] [--pod-index 1-10]" >&2
  echo "  Bundle 1: API + single key" >&2
  echo "  Bundle 2: API + multi-key management  (default)" >&2
  echo "  Bundle 3: API + multi-key + Virtual Desktop + UduChat" >&2
  echo "  Pod Index: 1-10 — which user slot to provision  (default 1)" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bundle)    BUNDLE="$2";    shift 2 ;;
    --pod-index) POD_INDEX="$2"; shift 2 ;;
    --help|-h)   usage ;;
    *) echo "Unknown option: $1" >&2; usage ;;
  esac
done

case "$BUNDLE" in
  1|2|3) ;;
  *) echo "ERROR: --bundle must be 1, 2, or 3 (got: $BUNDLE)" >&2; exit 1 ;;
esac

if ! [[ "$POD_INDEX" =~ ^([1-9]|10)$ ]]; then
  echo "ERROR: --pod-index must be 1-10 (got: $POD_INDEX)" >&2; exit 1
fi

BUNDLE_FILE="$SCRIPT_DIR/bundles/bundle${BUNDLE}.env"
[ -f "$BUNDLE_FILE" ] || { echo "ERROR: Bundle file not found: $BUNDLE_FILE" >&2; exit 1; }

# Source bundle — sets MODEL, OLLAMA_NUM_CTX, RATE_LIMIT_RPM, BUNDLE_NAME, GPU_TARGET, VD_PASS (bundle3)
# shellcheck source=/dev/null
source "$BUNDLE_FILE"

echo "================================================"
echo " AGH LLM Suite — Bundle ${BUNDLE}: ${BUNDLE_NAME}"
echo " GPU: ${GPU_TARGET} | Model: ${MODEL} | Pod: ${POD_INDEX}"
echo "================================================"

# Model: user selection from startup.sh takes priority over bundle default
if [ -z "${MODEL_TAG:-}" ]; then
  # Fallback — construct tag from bundle's MODEL field (legacy / direct invocation)
  MODEL_TAG="hf.co/unsloth/${MODEL}:UD-Q4_K_XL"
  MODEL_SHORT="${MODEL}"
fi

# Export all vars for bootstrap.sh
export BUNDLE OLLAMA_NUM_CTX RATE_LIMIT_RPM BUNDLE_NAME GPU_TARGET
export MODEL_TAG MODEL_SHORT
export POD_INDEX SCRIPT_DIR

# Optional secrets (auto-generated by bootstrap.sh if empty)
export LLM_API_KEY="${LLM_API_KEY:-}"
export ADMIN_TOKEN="${ADMIN_TOKEN:-}"
export WEBHOOK_URL="${WEBHOOK_URL:-}"
export TUNNEL_TOKEN="${TUNNEL_TOKEN:-}"
export VD_PASS="${VD_PASS:-changeme}"

exec bash "$SCRIPT_DIR/bootstrap.sh"
